data-path = ../../data/timing/qm9_100k.csv
save-dir = small_data
num-workers = 8
batch-size = 64
accelerator = gpu
devices = 1
multi-hot-atom-featurizer-mode = V2
ensemble-size = 3
message-hidden-dim = 300
depth = 3
ffn-hidden-dim = 300
ffn-num-layers = 1
dropout = 0.0
activation = RELU
aggregation = mean
task-type = regression
warmup-epochs = 2
init-lr = 0.0001
max-lr = 0.001
final-lr = 0.0001
epochs = 50
splits-file = ?
data-seed = 0
pytorch-seed = 0
